name: Build application

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.io/lodik

    steps:
      - uses: actions/checkout@v1
      - name: Set up Azul JDK 1.8 and SBT
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build
        run: sbt "^compile; docker:publish"
